export type TokenProvider = 'xStocks' | 'Ondo' | 'PreStocks';

export interface StockToken {
  symbol: string;
  name: string;
  mint: string;
  provider: TokenProvider;
  sector?: string;
  company?: string; // shared key for bundling same company across providers
}

// ─── xStocks (45 tokens) ───────────────────────────────────────────────────────

export const XSTOCKS: StockToken[] = [
  // Tech
  { symbol: 'AAPLx', name: 'Apple', mint: 'XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp', provider: 'xStocks', sector: 'Tech', company: 'AAPL' },
  { symbol: 'MSFTx', name: 'Microsoft', mint: 'XspzcW1PRtgf6Wj92HCiZdjzKCyFekVD8P5Ueh3dRMX', provider: 'xStocks', sector: 'Tech', company: 'MSFT' },
  { symbol: 'NVDAx', name: 'NVIDIA', mint: 'Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh', provider: 'xStocks', sector: 'Tech', company: 'NVDA' },
  { symbol: 'AMZNx', name: 'Amazon', mint: 'Xs3eBt7uRfJX8QUs4suhyU8p2M6DoUDrJyWBa8LLZsg', provider: 'xStocks', sector: 'Tech' },
  { symbol: 'METAx', name: 'Meta', mint: 'Xsa62P5mvPszXL1krVUnU5ar38bBSVcWAB6fmPCo5Zu', provider: 'xStocks', sector: 'Tech' },
  { symbol: 'GOOGLx', name: 'Alphabet', mint: 'XsCPL9dNWBMvFtTmwcCA5v3xWPSMEBCszbQdiLLq6aN', provider: 'xStocks', sector: 'Tech', company: 'GOOGL' },
  { symbol: 'ACNx', name: 'Accenture', mint: 'Xs5UJzmCRQ8DWZjskExdSQDnbE6iLkRu2jjrRAB1JSU', provider: 'xStocks', sector: 'Tech' },
  { symbol: 'INTCx', name: 'Intel', mint: 'XshPgPdXFRWB8tP1j82rebb2Q9rPgGX37RuqzohmArM', provider: 'xStocks', sector: 'Tech', company: 'INTC' },
  { symbol: 'ORCLx', name: 'Oracle', mint: 'XsjFwUPiLofddX5cWFHW35GCbXcSu1BCUGfxoQAQjeL', provider: 'xStocks', sector: 'Tech', company: 'ORCL' },
  { symbol: 'CSCOx', name: 'Cisco', mint: 'Xsr3pdLQyXvDJBFgpR5nexCEZwXvigb8wbPYp4YoNFf', provider: 'xStocks', sector: 'Tech' },
  { symbol: 'AVGOx', name: 'Broadcom', mint: 'XsgSaSvNSqLTtFuyWPBhK9196Xb9Bbdyjj4fH3cPJGo', provider: 'xStocks', sector: 'Tech', company: 'AVGO' },
  { symbol: 'MRVLx', name: 'Marvell Technology', mint: 'XsuxRGDzbLjnJ72v74b7p9VY6N66uYgTCyfwwRjVCJA', provider: 'xStocks', sector: 'Tech' },


  // EV
  { symbol: 'TSLAx', name: 'Tesla', mint: 'XsDoVfqeBukxuZHWhdvWHBhgEHjGNst4MLodqsJHzoB', provider: 'xStocks', sector: 'EV' },

  // Crypto
  { symbol: 'COINx', name: 'Coinbase', mint: 'Xs7ZdzSHLU9ftNJsii5fCeJhoRWSC32SQGzGQtePxNu', provider: 'xStocks', sector: 'Crypto' },
  { symbol: 'CRCLx', name: 'Circle', mint: 'XsueG8BtpquVJX9LVLLEGuViXUungE6WmK5YZ3p3bd1', provider: 'xStocks', sector: 'Crypto', company: 'CRCL' },
  { symbol: 'MSTRx', name: 'MicroStrategy', mint: 'XsP7xzNPvEHS1m6qfanPUGjNmdnmsLKEoNAnHjdxxyZ', provider: 'xStocks', sector: 'Crypto' },
  { symbol: 'DFDVx', name: 'DeFi Dev Corp', mint: 'Xs2yquAgsHByNzx68WJC55WHjHBvG9JsMB7CWjTLyPy', provider: 'xStocks', sector: 'Crypto' },
  { symbol: 'AMBRx', name: 'Amber', mint: 'XsaQTCgebC2KPbf27KUhdv5JFvHhQ4GDAPURwrEhAzb', provider: 'xStocks', sector: 'Crypto' },

  // Finance
  { symbol: 'HOODx', name: 'Robinhood', mint: 'XsvNBAYkrDRNhA7wPHQfX3ZUXZyZLdnCQDfHZ56bzpg', provider: 'xStocks', sector: 'Finance' },
  { symbol: 'BRK.Bx', name: 'Berkshire Hathaway', mint: 'Xs6B6zawENwAbWVi7w92rjazLuAr5Az59qgWKcNb45x', provider: 'xStocks', sector: 'Finance' },
  { symbol: 'MAx', name: 'Mastercard', mint: 'XsApJFV9MAktqnAc6jqzsHVujxkGm9xcSUffaBoYLKC', provider: 'xStocks', sector: 'Finance' },
  { symbol: 'JPMx', name: 'JPMorgan', mint: 'XsMAqkcKsUewDrzVkait4e5u4y8REgtyS7jWgCpLV2C', provider: 'xStocks', sector: 'Finance', company: 'JPM' },
  { symbol: 'Vx', name: 'Visa', mint: 'XsqgsbXwWogGJsNcVZ3TyVouy2MbTkfCFhCGGGcQZ2p', provider: 'xStocks', sector: 'Finance' },

  // Media
  { symbol: 'NFLXx', name: 'Netflix', mint: 'XsEH7wWfJJu2ZT3UCFeVfALnVA6CP5ur7Ee11KmzVpL', provider: 'xStocks', sector: 'Media', company: 'NFLX' },
  { symbol: 'CMCSAx', name: 'Comcast', mint: 'XsvKCaNsxg2GN8jjUmq71qukMJr7Q1c5R2Mk9P8kcS8', provider: 'xStocks', sector: 'Media' },

  // Consumer
  { symbol: 'MCDx', name: "McDonald's", mint: 'XsqE9cRRpzxcGKDXj1BJ7Xmg4GRhZoyY1KpmGSxAWT2', provider: 'xStocks', sector: 'Consumer', company: 'MCD' },
  { symbol: 'KOx', name: 'Coca-Cola', mint: 'XsaBXg8dU5cPM6ehmVctMkVqoiRG2ZjMo1cyBJ3AykQ', provider: 'xStocks', sector: 'Consumer', company: 'KO' },
  { symbol: 'WMTx', name: 'Walmart', mint: 'Xs151QeqTCiuKtinzfRATnUESM2xTU6V9Wy8Vy538ci', provider: 'xStocks', sector: 'Consumer', company: 'WMT' },
  { symbol: 'PGx', name: 'Procter & Gamble', mint: 'XsYdjDjNUygZ7yGKfQaB6TxLh2gC6RRjzLtLAGJrhzV', provider: 'xStocks', sector: 'Consumer', company: 'PG' },
  { symbol: 'PEPx', name: 'PepsiCo', mint: 'Xsv99frTRUeornyvCfvhnDesQDWuvns1M852Pez91vF', provider: 'xStocks', sector: 'Consumer' },

  // Health
  { symbol: 'UNHx', name: 'UnitedHealth', mint: 'XszvaiXGPwvk2nwb3o9C1CX4K6zH8sez11E6uyup6fe', provider: 'xStocks', sector: 'Health' },
  { symbol: 'MRKx', name: 'Merck', mint: 'XsnQnU7AdbRZYe2akqqpibDdXjkieGFfSkbkjX1Sd1X', provider: 'xStocks', sector: 'Health' },
  { symbol: 'ABTx', name: 'Abbott Labs', mint: 'XsHtf5RpxsQ7jeJ9ivNewouZKJHbPxhPoEy6yYvULr7', provider: 'xStocks', sector: 'Health' },
  { symbol: 'JNJx', name: 'Johnson & Johnson', mint: 'XsGVi5eo1Dh2zUpic4qACcjuWGjNv8GCt3dm5XcX6Dn', provider: 'xStocks', sector: 'Health' },
  { symbol: 'AZNx', name: 'AstraZeneca', mint: 'Xs3ZFkPYT2BN7qBMqf1j1bfTeTm1rFzEFSsQ1z3wAKU', provider: 'xStocks', sector: 'Health' },
  { symbol: 'LLYx', name: 'Eli Lilly', mint: 'Xsnuv4omNoHozR6EEW5mXkw8Nrny5rB3jVfLqi6gKMH', provider: 'xStocks', sector: 'Health', company: 'LLY' },
  { symbol: 'TMOx', name: 'Thermo Fisher', mint: 'Xs8drBWy3Sd5QY3aifG9kt9KFs2K3PGZmx7jWrsrk57', provider: 'xStocks', sector: 'Health' },

  // ETF
  { symbol: 'SPYx', name: 'S&P 500 ETF', mint: 'XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W', provider: 'xStocks', sector: 'ETF' },
  { symbol: 'QQQx', name: 'Nasdaq 100 ETF', mint: 'Xs8S1uUs1zvS2p7iwtsG3b6fkhpvmwz4GYU3gWAmWHZ', provider: 'xStocks', sector: 'ETF', company: 'QQQ' },
  { symbol: 'TQQQx', name: 'ProShares UltraPro QQQ', mint: 'XsjQP3iMAaQ3kQScQKthQpx9ALRbjKAjQtHg6TFomoc', provider: 'xStocks', sector: 'ETF' },

  // Commodity
  { symbol: 'GLDx', name: 'Gold ETF', mint: 'Xsv9hRk1z5ystj9MhnA7Lq4vjSsLwzL2nxrwmwtD3re', provider: 'xStocks', sector: 'Commodity' },

  // Energy
  { symbol: 'CVXx', name: 'Chevron', mint: 'XsNNMt7WTNA2sV3jrb1NNfNgapxRF5i4i6GcnTRRHts', provider: 'xStocks', sector: 'Energy', company: 'CVX' },
  { symbol: 'XOMx', name: 'ExxonMobil', mint: 'XsaHND8sHyfMfsWPj6kSdd5VwvCayZvjYgKmmcNL5qh', provider: 'xStocks', sector: 'Energy' },

  // Industrial
  { symbol: 'LINx', name: 'Linde', mint: 'XsSr8anD1hkvNMu8XQiVcmiaTP7XGvYu7Q58LdmtE8Z', provider: 'xStocks', sector: 'Industrial' },

  // Retail
  { symbol: 'GMEx', name: 'GameStop', mint: 'Xsf9mBktVB9BSU5kf4nHxPq5hCBJ2j2ui3ecFGxPRGc', provider: 'xStocks', sector: 'Retail' },
];

// ─── PreStocks (6 tokens) ──────────────────────────────────────────────────────

export const PRESTOCKS: StockToken[] = [
  { symbol: 'OPENAI', name: 'OpenAI', mint: 'PreweJYECqtQwBtpxHL171nL2K6umo692gTm7Q3rpgF', provider: 'PreStocks', sector: 'AI' },
  { symbol: 'ANTHROPIC', name: 'Anthropic', mint: 'Pren1FvFX6J3E4kXhJuCiAD5aDmGEb7qJRncwA8Lkhw', provider: 'PreStocks', sector: 'AI' },
  { symbol: 'SPACEX', name: 'SpaceX', mint: 'PreANxuXjsy2pvisWWMNB6YaJNzr7681wJJr2rHsfTh', provider: 'PreStocks', sector: 'Aerospace' },
  { symbol: 'ANDURIL', name: 'Anduril', mint: 'PresTj4Yc2bAR197Er7wz4UUKSfqt6FryBEdAriBoQB', provider: 'PreStocks', sector: 'Defense' },
  { symbol: 'POLYMARKET', name: 'Polymarket', mint: 'Pre8AREmFPtoJFT8mQSXQLh56cwJmM7CFDRuoGBZiUP', provider: 'PreStocks', sector: 'Prediction' },
  { symbol: 'KALSHI', name: 'Kalshi', mint: 'PreLWGkkeqG1s4HEfFZSy9moCrJ7btsHuUtfcCeoRua', provider: 'PreStocks', sector: 'Prediction' },
];

// ─── Ondo (201 tokens) ─────────────────────────────────────────────────────────

export const ONDO_TOKENS: StockToken[] = [
  { symbol: 'SLVon', name: "iShares Silver Trust", mint: 'iy11ytbSGcUnrjE6Lfv78TFqxKyUESfku1FugS9ondo', provider: 'Ondo', sector: 'Commodity' },
  { symbol: 'CRCLon', name: "Circle Internet Group", mint: '6xHEyem9hmkGtVq6XGCiQUGpPsHBaoYuYdFNZa5ondo', provider: 'Ondo', sector: 'Crypto' },
  { symbol: 'Von', name: "Visa", mint: 'kxEW4oJL75K37VeXaZF1ynbHQATQwhECQKN1374ondo', provider: 'Ondo', sector: 'Finance' },
  { symbol: 'TLTon', name: "iShares 20+ Year Treasury Bond ETF", mint: 'KaSLSWByKy6b9FrCYXPEJoHmLpuFZtTCJk1F1Z9ondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'CVXon', name: "Chevron", mint: '7tgKziACteG26VjV5xKufojKxwTgCFyTwmWUmz5ondo', provider: 'Ondo', sector: 'Energy' },
  { symbol: 'PDDon', name: "PDD Holdings", mint: 'PnjETBCLC318DRejo9cMQKAmET9PvW8AEFGWMNtondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'QQQon', name: "Invesco QQQ", mint: 'HrYNm6jTQ71LoFphjVKBTdAE4uja7WsmLG8VxB8ondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'COPXon', name: "Global X Copper Miners ETF", mint: 'X7j77hTmjZJbepkXXBcsEapM8qNgdfihkFj6CZ5ondo', provider: 'Ondo', sector: 'Commodity' },
  { symbol: 'MSFTon', name: "Microsoft", mint: 'FRmH6iRkMr33DLG6zVLR7EM4LojBFAuq6NtFzG6ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'NFLXon', name: "Netflix", mint: 'g4KnPrxPLeeKkwvDmZFMtYQPM64eHeShbD55vK6ondo', provider: 'Ondo', sector: 'Media' },
  { symbol: 'MCDon', name: "McDonald's", mint: 'EUbJjmDt8JA222M91bVLZs211siZ2jzbFArH9N3ondo', provider: 'Ondo', sector: 'Consumer' },
  { symbol: 'PLTRon', name: "Palantir Technologies", mint: 'HfsnTS5qtdStwec9DfBrunRqnAMYMMz1kjv9Hu9ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'IBMon', name: "IBM", mint: 'C8bZkgSxXkyT1RgxByp2teJ24hgimPLoyEYoNa9ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'MUon', name: "Micron Technology", mint: 'Fz9edBpaURPPzpKVRR1A8PENYDEgHqwx5D5th28ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'CRMon', name: "Salesforce", mint: '7D7ukbcnUNYt7Et5vtsDZhAy28MKu9pkHka1Hp9ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'IEFAon', name: "iShares Core MSCI EAFE ETF", mint: 'C9J9vZ8N79GzzxFoRkPWCkGtMKU8akg4FhUk4r9ondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'SPGIon', name: "S&P Global", mint: 'JrTYw7A9jihX5TwpRStYviEbsYf2X2VJpZ13719ondo', provider: 'Ondo', sector: 'Finance' },
  { symbol: 'ORCLon', name: "Oracle", mint: 'GmDADFpfwjfzZq9MfCafMDTS69MgVjtzD7Fd9a4ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'JDon', name: "JD.com", mint: 'E1aUS5nyv7kaBzdQzPVJW5zfaMgoUJpKYzdnFS2ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'PYPLon', name: "PayPal", mint: 'hM7B3UQTTR81mS27SxDDPzBbjejmo8fnpFjzgv9ondo', provider: 'Ondo', sector: 'Finance' },
  { symbol: 'RGTIon', name: "Rigetti Computing", mint: 'dwEPNKQab3iwRmjGvZPXhAmws1W5NsQGwuXwi8oondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'NVDAon', name: "NVIDIA", mint: 'gEGtLTPNQ7jcg25zTetkbmF7teoDLcrfTnQfmn2ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'QBTSon', name: "D-Wave Quantum", mint: 'hqJXutLF6f7DxStrWCrnZDfXzbNTZmvi3KheVi6ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'BABAon', name: "Alibaba", mint: '1zvb9ELBFShBCWKEk5jRTJAaPAwtVt7quEXx1X4ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'NVOon', name: "Novo Nordisk", mint: 'GeV7S8vjP8qdYZpdGv2Xi6e7MUMCk8NAAp2z7g5ondo', provider: 'Ondo', sector: 'Health' },
  { symbol: 'IWMon', name: "iShares Russell 2000 ETF", mint: 'dvj2kKFSyjpnyYSYppgFdAEVfgjMEoQGi9VaV23ondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'ADBEon', name: "Adobe", mint: '12Rh6JhfW4X5fKP16bbUdb4pcVCKDHFB48x8GG33ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'TSMon', name: "TSMC", mint: 'keybg184d4vyXeQdFqs4o99YsMg7xBthxTJ6Ky3ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'AVGOon', name: "Broadcom", mint: '1FWZtdWN7y38BSXGzbs8D6Shk88oL9atDNgbVz9ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'WMTon', name: "Walmart", mint: 'LZddqAqKqJW9oMZSjTxCUmbmzBRQtv9gMkD9hZ3ondo', provider: 'Ondo', sector: 'Consumer' },
  { symbol: 'AAPLon', name: "Apple", mint: '123mYEnRLM2LLYsJW3K6oyYh8uP1fngj732iG638ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'GOOGLon', name: "Alphabet Class A", mint: 'bbahNA5vT9WJeYft8tALrH1LXWffjwqVoUbqYa1ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'AMDon', name: "AMD", mint: '14diAn5z8kjrKwSC8WLqvBqqe5YmihJhjxRxd8Z6ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'PFEon', name: "Pfizer", mint: 'Gwh9fPsX1qWATXy63vNaJnAFfwebWQtZaVmPko6ondo', provider: 'Ondo', sector: 'Health' },
  { symbol: 'IWNon', name: "iShares Russell 2000 Value ETF", mint: 'DX7g7WNjDpVzNK9CG81v7wb6ZbiNzYfkdzH2Xs5ondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'AGGon', name: "iShares Core US Aggregate Bond ETF", mint: '13qTjKx53y6LKGGStiKeieGbnVx3fx1bbwopKFb3ondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'IJHon', name: "iShares Core S&P MidCap ETF", mint: 'cfPLN9WXD2BTkbZhRZMVXPmVSiRo44hJWRtnaC8ondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'SBUXon', name: "Starbucks", mint: 'iPFqjcZQTNMNXA4kbShbMhfAVD8yr8Uq9UtXMV6ondo', provider: 'Ondo', sector: 'Consumer' },
  { symbol: 'KOon', name: "Coca-Cola", mint: 'e6G4pfFcrdKxJuZ4YXixRFfMbpMvgXG2Mjcus71ondo', provider: 'Ondo', sector: 'Consumer' },
  { symbol: 'EEMon', name: "iShares MSCI Emerging Markets ETF", mint: '916SDKz7y5ZcEZC9CtnQ5Djs1Y8Yv3UAPb6bak8ondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'LMTon', name: "Lockheed Martin", mint: 'EoReHwUnGGekbXFHLj5rbCVKiwWqu32GrETMfw4ondo', provider: 'Ondo', sector: 'Defense' },
  { symbol: 'IVVon', name: "iShares Core S&P 500 ETF", mint: 'CqW2pd6dCPG9xKZfAsTovzDsMmAGKJSDBNcwM96ondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'PGon', name: "Procter & Gamble", mint: 'GZ8v4NdSG7CTRZqHMgNsTPRULeVi8CpdWd9wZY8ondo', provider: 'Ondo', sector: 'Consumer' },
  { symbol: 'JPMon', name: "JPMorgan Chase", mint: 'E5Gczsavxcomqf6Cw1sGCKLabL1xYD2FzKxVoB4ondo', provider: 'Ondo', sector: 'Finance' },
  { symbol: 'EFAon', name: "iShares MSCI EAFE ETF", mint: 'AbvryMGnaba9oADMZk8Vp2Av6MtczsncGyfWaC4ondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'LLYon', name: "Eli Lilly", mint: 'eGGxZwNSfuNKRqQLKaz2hc4QkA2mau7skyxPdj7ondo', provider: 'Ondo', sector: 'Health' },
  { symbol: 'INTCon', name: "Intel", mint: 'cJpUMp5R7rZ6fGeLHbHhrRuJzK9mkyKDjZqNpT3ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'IAUon', name: "iShares Gold Trust", mint: 'M77ZvkZ8zW5udRbuJCbuwSwavRa7bGAZYMTwru8ondo', provider: 'Ondo', sector: 'Commodity' },
  { symbol: 'PEPon', name: "PepsiCo", mint: 'gud6b3fYekjhMG5F818BALwbg2vt4JKoow59Md9ondo', provider: 'Ondo', sector: 'Consumer' },
  { symbol: 'IEMGon', name: "iShares Core MSCI Emerging Markets ETF", mint: 'cdVNL7wK8mf1UCDqM6zdrziRv4hmvqWhXeTcck2ondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'TMon', name: "Toyota", mint: 'kbmF7ERJWMaaDswMprrH9gHSLya5D2RMBNgKqg3ondo', provider: 'Ondo', sector: 'Auto' },
  { symbol: 'BLKon', name: "BlackRock", mint: '5H1VpMzRuoNtRbPTRCz35ETtEUtnkt8hJuQb9v7ondo', provider: 'Ondo', sector: 'Finance' },
  { symbol: 'METAon', name: "Meta Platforms", mint: 'fDxs5y12E7x7jBwCKBXGqt71uJmCWsAQ3Srkte6ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'AMZNon', name: "Amazon", mint: '14Tqdo8V1FhzKsE3W2pFsZCzYPQxxupXRcqw9jv6ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'BMNRon', name: "BitMine Immersion", mint: 'MYXqkDYbzr7vjXAz2BapR4AiYRXzoikGirrLoRzondo', provider: 'Ondo', sector: 'Crypto' },
  { symbol: 'IWFon', name: "iShares Russell 1000 Growth ETF", mint: 'dSHPFuMMjZqt7xDYGWrexXTSkdEZAiZngqymQF2ondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'ASMLon', name: "ASML Holding NV", mint: '1eLZPRsn8bAKmoxsqDMH9Q2m2k7GMNp6RLSQGm8ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'MSTRon', name: "MicroStrategy", mint: 'FSz4ouiqXpHuGPcpacZfTzbMjScoj5FfzHkiyu2ondo', provider: 'Ondo', sector: 'Crypto' },
  { symbol: 'SPYon', name: "SPDR S&P 500 ETF", mint: 'k18WJUULWheRkSpSquYGdNNmtuE2Vbw1hpuUi92ondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'TSLAon', name: "Tesla", mint: 'KeGv7bsfR4MheC1CkmnAVceoApjrkvBhHYjWb67ondo', provider: 'Ondo', sector: 'EV' },
  { symbol: 'TIPon', name: "iShares TIPS Bond ETF", mint: 'k6BPp2Xmf2TYgrZiUyWfUoZBKeqaDbvPoAVgSx2ondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'ITOTon', name: "iShares Core S&P Total US Stock Market ETF", mint: 'CPWkMURVvcnX8hGjqCTb8i5LkzV3VSvyk7SeJi8ondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'USOon', name: "United States Oil Fund", mint: 'rpydAzWdCy85HEmoQkH5PVxYtDYQWjmLxgHHadxondo', provider: 'Ondo', sector: 'Commodity' },
  { symbol: 'REMXon', name: "VanEck Rare Earth ETF", mint: 'tiitb2Z1HtpB2DpVr6V7tdCFS3jmTinLeuGj9EVondo', provider: 'Ondo', sector: 'Commodity' },
  { symbol: 'SOFIon', name: "SoFi Technologies", mint: 'mqL8yXQpeSvc7NgrAtLLPtRvUiWyLoG5RWLv16iondo', provider: 'Ondo', sector: 'Finance' },
  { symbol: 'DGRWon', name: "WisdomTree US Quality Dividend Growth", mint: 'gnoSQSNTNZHViqVfxCcPDVxcRA29mrJL7C6JqYLondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'SCHWon', name: "Charles Schwab", mint: 'cnc6M1zXLdrGR5LAQVcaJDfgezMiVWNtGQsVy1Kondo', provider: 'Ondo', sector: 'Finance' },
  { symbol: 'GRNDon', name: "Grindr", mint: 'Gc1aT3ay7FXL3qdAW7cNSXYPDsGavy7qiACuxwxondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'VTIon', name: "Vanguard Total Stock Market ETF", mint: 'jCCU4GwukjNxAXJowG2S4KCrr5g6YyUB61WHYvGondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'IRENon', name: "IREN", mint: '13QHuepdhtJ3urNsV9i1hdL8nQoca2G7ZaLzb5FYondo', provider: 'Ondo', sector: 'Crypto' },
  { symbol: 'QCOMon', name: "Qualcomm", mint: 'hrmX7MV5hifoaBVjnrdpz698yABxrbBNAcWtWo9ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'TQQQon', name: "ProShares UltraPro QQQ", mint: '14W1itEkV7k1W819mLSknFTaMmkCtPokbF2tRkPUondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'COINon', name: "Coinbase", mint: '5u6KDiNJXxX4rGMfYT4BApZQC5CuDNrG6MHkwp1ondo', provider: 'Ondo', sector: 'Crypto' },
  { symbol: 'CSCOon', name: "Cisco Systems", mint: '7DWcZE1uVc8m2mf9pV8KNov28ET7HsvHkhrhgr9ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'DISon', name: "Disney", mint: 'mJf1xT3suXtkXBCfZcE9oUUuyxkvSgqYBWiX7v1ondo', provider: 'Ondo', sector: 'Media' },
  { symbol: 'MRNAon', name: "Moderna", mint: '14VP7DvCAdBCc5XGNZkPt6zhtPzJrWWS64Koxtxyondo', provider: 'Ondo', sector: 'Health' },
  { symbol: 'HYGon', name: "iBoxx High Yield Corporate Bond ETF", mint: 'c5ug15fwZRfQhhVa6LHscFY33ebVDHcVCezYpj7ondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'NIOon', name: "NIO", mint: 'yQ37dFiGAbzrb2FRAEhGNzRy5zFfoYGWYhAepFEondo', provider: 'Ondo', sector: 'EV' },
  { symbol: 'LRCXon', name: "Lam Research", mint: 'wFJoeEYpKg9oRhyJy6BWTT3J95gmXBLvoeikDQNondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'SOUNon', name: "SoundHound AI", mint: 'vE2qArmjto6VfeMngyGAnzp2ipLYeXsxiARDnnXondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'LIon', name: "Li Auto", mint: 'v12TwfofSbvVqQ5N5KGG4d3J8rtEi4BjGfn2apyondo', provider: 'Ondo', sector: 'EV' },
  { symbol: 'CLOIon', name: "VanEck CLO ETF", mint: 'ucQ3VfWAx9pkCN4Kg84zE56FtB4FJN2kQH4ArYYondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'DBCon', name: "Invesco DB Commodity Index", mint: 'td1aY5AvYQuwGD75qNq9aPipMexraN9mQXJwqifondo', provider: 'Ondo', sector: 'Commodity' },
  { symbol: 'NEEon', name: "NextEra Energy", mint: 't7eN6cGwRMFaZvsNW2SmVwkedmHtDdrxA4ycNE5ondo', provider: 'Ondo', sector: 'Energy' },
  { symbol: 'CLOAon', name: "iShares AAA CLO Active ETF", mint: 't71FyTYHVkPAb5g48adDHmkVxXYbUuP2eq6jDZLondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'PINSon', name: "Pinterest", mint: 'sxyg1VTSzy5zYANUK7hntNtmFAWoXGJq95AcHuVondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'PSQon', name: "ProShares Short QQQ", mint: 'qKtU9A7ij34XmtxaSzYfxCpkgAZzzFsqnUb2kW2ondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'XOMon', name: "Exxon Mobil", mint: 'qCYD74QnXzd9pzv6pGHQKJVwoibL6sNcPQDnpDiondo', provider: 'Ondo', sector: 'Energy' },
  { symbol: 'TMUSon', name: "T-Mobile US", mint: 'pDY4GPJfZcNETPG7myXeafQfgJqqVkn81bMYDyfondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'OPENon', name: "Opendoor Technologies", mint: 'ou1uE526v7zmUYP2qCb2LJgfXAyWAtWS9SETtr8ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'USFRon', name: "WisdomTree Floating Rate Treasury", mint: 'o6U1Sm6Vd7EofMyCrL28mrp2QLzgYGgjveHiEQ5ondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'BINCon', name: "iShares Flexible Income Active ETF", mint: 'mhZ69E1vDnAsQJXAwarLYSX5tmgeMajXBJ2rXAcondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'GRABon', name: "Grab Holdings", mint: 'm9GcsVgdjaL3KsdtSFHimnhtsUMpTHkjtwEG4Tzondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'OKLOon', name: "Oklo", mint: 'm6oDLvJT7rY7M1TxuLWP3pWmAPg2cCWDQR1NKiEondo', provider: 'Ondo', sector: 'Energy' },
  { symbol: 'UNHon', name: "UnitedHealth", mint: 'kPBGL8vAwKN3UGmr9cjkM2dU79SC3nzTC9yu7F8ondo', provider: 'Ondo', sector: 'Health' },
  { symbol: 'SPOTon', name: "Spotify", mint: 'jzCvs2Pk8tDcfsFRqnEMjurgaQW4iQfEkandUR8ondo', provider: 'Ondo', sector: 'Media' },
  { symbol: 'SMCIon', name: "Super Micro Computer", mint: 'jLca79XzcewRuBZyaJxVxuKpUHcEix1X4CP1RP9ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'SHOPon', name: "Shopify", mint: 'ivdDracs2s7jCP698dJXKSEQdVrNj9hasJL1Uq1ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'FTGCon', name: "First Trust Global Tactical Commodity", mint: 'ivBnfPTyuHDNWmMSnbavckhJK6SHZW8h77nZKsEondo', provider: 'Ondo', sector: 'Commodity' },
  { symbol: 'VZon', name: "Verizon", mint: 'igu1coP6n3GPaWmbd8J9Z7UAyLpV254uQFFNfydondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'SBETon', name: "SharpLink Gaming", mint: 'iLDu2jjp2i3Uqc2Vm7K7GLiUj3hR4Un49MtD7c4ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'RIOTon', name: "Riot Platforms", mint: 'i6f3DvZBuLpnGSqS8x6WPeStJ7jNe5KewD6afD5ondo', provider: 'Ondo', sector: 'Crypto' },
  { symbol: 'GLDon', name: "SPDR Gold Shares", mint: 'hWfiw4mcxT8rnNFkk6fsCQSxoxgZ9yVhB6tyeVcondo', provider: 'Ondo', sector: 'Commodity' },
  { symbol: 'VSTon', name: "Vistra", mint: 'h6MW8GFpfzxFa1JNn6hZNnBF3t4fj9SHAXKy6LXondo', provider: 'Ondo', sector: 'Energy' },
  { symbol: 'OPRAon', name: "Opera", mint: 'gbHFTMkuMQUy5xrgoCBdaQ2XYvNyjWAYcnRPh9Condo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'NKEon', name: "Nike", mint: 'g646pcdG2Rt5DH9WZzL7VVnVDWCCMTTrnktwE74ondo', provider: 'Ondo', sector: 'Consumer' },
  { symbol: 'WULFon', name: "Terawulf", mint: 'exYfSJt6Fgfhfnp3bAD4roYy97hLF9npjYaLyEXondo', provider: 'Ondo', sector: 'Crypto' },
  { symbol: 'LOWon', name: "Lowe's", mint: 'edLdFJVVR532qhcrNTJjLAmhmyV7NsctbWVokMBondo', provider: 'Ondo', sector: 'Consumer' },
  { symbol: 'BZon', name: "Kanzhun", mint: 'doPqjCxi6UkANkvMz5fSuYGEo5PGppVpTZMeB5vondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'CRWDon', name: "CrowdStrike", mint: 'cdKfoNjbXgnSuxvoajhtH3uixfZhq1YXhQsS1Rwondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'BTGon', name: "B2Gold", mint: 'cBnVXDyZgaaLZM18wAmqsUKnRUFAEJWbq6VuUoaondo', provider: 'Ondo', sector: 'Commodity' },
  { symbol: 'MRKon', name: "Merck", mint: 'bn1fb8dwzafGePqNPrM8m8cbAKQiFqeEPuZkPySondo', provider: 'Ondo', sector: 'Health' },
  { symbol: 'HIMSon', name: "Hims & Hers Health", mint: 'bdh3njeo19d2TBLAKTGvCWdSoArfVw8uZBAJHY4ondo', provider: 'Ondo', sector: 'Health' },
  { symbol: 'GMEon', name: "GameStop", mint: 'aznKt8v32CwYMEcTcB4bGTv8DXWStCpHrcCtyy7ondo', provider: 'Ondo', sector: 'Retail' },
  { symbol: 'EQIXon', name: "Equinix", mint: 'aheEdmuryJU8ymy8LjYheZH5i2BW1UMsfuWQKD2ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'GEon', name: "General Electric", mint: 'aTBfDuLRqYHBiG82bHA7DzwjSDTFre2dRtGH3S5ondo', provider: 'Ondo', sector: 'Industrial' },
  { symbol: 'FIGon', name: "Figma", mint: 'aLDdFsr3VTUQaHFK6yNvQxztvxQ8nxW4AMuSGC7ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'SOon', name: "Southern Company", mint: 'aKzjn2ZdWySSGPSSDTY2HUpcSCmemSahTXihrpyondo', provider: 'Ondo', sector: 'Energy' },
  { symbol: 'SNAPon', name: "Snap", mint: 'a2cXfonVgQ6cKB4Lm8YZsPry39VZSA562bwmRSiondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'FIGRon', name: "Figure Technology Solutions", mint: 'ZmHxc6Gt27RJKxD2ay6UL4n9yQ7mKAq4XZQUeVhondo', provider: 'Ondo', sector: 'Finance' },
  { symbol: 'NTESon', name: "NetEase", mint: 'YeK2TdPtGLAme3Phg4pb1GBN2YxKgX5UNVyD4asondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'BBAIon', name: "BigBear.ai Holdings", mint: 'YXE7mph6XhsgnyezkMEcTuohSuWhbLWfwx2Hh6mondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'MPon', name: "MP Materials", mint: 'XwFm5GiKPVTvPiEbQpdc6vJbFEpsUXRMf6TcSxnondo', provider: 'Ondo', sector: 'Commodity' },
  { symbol: 'COPon', name: "ConocoPhillips", mint: 'X68p9qTpEMkR1TLpXUP2ZJo8PG4Qge2Y2ZLdjA2ondo', provider: 'Ondo', sector: 'Energy' },
  { symbol: 'BACon', name: "Bank of America", mint: 'Wk8gC6iTNp8dqd4ghkJ3h1giiUnyhykwHh7tYWjondo', provider: 'Ondo', sector: 'Finance' },
  { symbol: 'CIFRon', name: "Cipher Mining", mint: 'WNZBSkNBNP3Ct1pcFn6Fu4sZQFhnu48EsM9voCEondo', provider: 'Ondo', sector: 'Crypto' },
  { symbol: 'Ton', name: "AT&T", mint: 'WKMZummev5UcXz5nNKQZvTD6QjNSM2X58uwmDReondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'NIKLon', name: "Sprott Nickel Miners ETF", mint: 'V8LRV7kWjrx6Prke9oHEHNUiR122BVtyuPciTCTondo', provider: 'Ondo', sector: 'Commodity' },
  { symbol: 'PCGon', name: "PG&E", mint: 'UP5s1srLaHDc4SwJqLPa3A48x5R7ofN3hZWxWEZondo', provider: 'Ondo', sector: 'Energy' },
  { symbol: 'PLUGon', name: "Plug Power", mint: 'TnfswqdE1jAJ8sfnf5J7kSVLEH1cfpAYZ8MWmKfondo', provider: 'Ondo', sector: 'Energy' },
  { symbol: 'OSCRon', name: "Oscar Health", mint: 'ThwGDsXZ6iKubWuEQjmDxGwF3bUERDGbBXvcbjFondo', provider: 'Ondo', sector: 'Health' },
  { symbol: 'TMOon', name: "Thermo Fisher Scientific", mint: 'T699bgtXQw4CJ59rQ4VzLsupVQUzoL5RmuhHnKrondo', provider: 'Ondo', sector: 'Health' },
  { symbol: 'AMGNon', name: "Amgen", mint: 'SS6AEWhzRrxhL2cXzKKjhFt3rCzmHHGKmFyugDTondo', provider: 'Ondo', sector: 'Health' },
  { symbol: 'TLNon', name: "Talen Energy", mint: 'RTb54gpqAx6RpLAHRGnqQ3ciQ845CHqhg21ZzEJondo', provider: 'Ondo', sector: 'Energy' },
  { symbol: 'MTZon', name: "MasTec", mint: 'R3ywbVQ5t8LNmjQsn2Ngv43dSqyZscQwNag9G3Eondo', provider: 'Ondo', sector: 'Industrial' },
  { symbol: 'COFon', name: "Capital One", mint: 'R2uDbMtmHq5xSS5SserrovdRKdpiqnVBCd2AHLhondo', provider: 'Ondo', sector: 'Finance' },
  { symbol: 'Con', name: "Citigroup", mint: 'PjtfUiw6Hwd8PZ94EcUw8mBSYxp7SjjzSLeNTDKondo', provider: 'Ondo', sector: 'Finance' },
  { symbol: 'PALLon', name: "abrdn Physical Palladium ETF", mint: 'P7hTXnKk2d2DyqWnefp5BSroE1qjjKpKxg9SxQqondo', provider: 'Ondo', sector: 'Commodity' },
  { symbol: 'GEMIon', name: "Gemini Space Station", mint: 'NrTdGMA3ujUvWXkwXyZKnhoByb32KTjRh5Vo47yondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'CPNGon', name: "Coupang", mint: 'NKyzy31w2J7odLb2CW3Ft4fpKXkW3LBt1pvpkVLondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'HDon', name: "Home Depot", mint: 'MtEXKVN3Pcggy8MPA3eJr15H6SK3RXheScqj9qtondo', provider: 'Ondo', sector: 'Consumer' },
  { symbol: 'VRTon', name: "Vertiv", mint: 'MkN2TZSYTFBdMRLf9EVcfhstTwnazH8knd9hpepondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'ABBVon', name: "AbbVie", mint: 'MFerpBVGKZh2jXN7cbJdXRXQTp6j6pbSnSZrfWrondo', provider: 'Ondo', sector: 'Health' },
  { symbol: 'PANWon', name: "Palo Alto Networks", mint: 'M7hVQomhw4Q2D2op3HvBrZjHu9SryjNvD5haEZ1ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'PDBCon', name: "Invesco Optimum Yield Diversified Commodity", mint: 'M6agiXbNgy8Xon9ngiW4ZDPbMFcNCTMkMMkshZyondo', provider: 'Ondo', sector: 'Commodity' },
  { symbol: 'ADIon', name: "Analog Devices", mint: 'LmTMwmZLNZszn3qpjmnbhfP12U4qWDivaEBwSBSondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'WFCon', name: "Wells Fargo", mint: 'L6ZE5qCpVVSqLePz64CrwkgyWoPF9M7tB8BeFH4ondo', provider: 'Ondo', sector: 'Finance' },
  { symbol: 'VTVon', name: "Vanguard Value ETF", mint: 'KuiYLPVq65qixD9TgvxBC576C4gG6vVTCdbh2zFondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'ACHRon', name: "Archer Aviation", mint: 'KcCVQxG9LhFYP5o9DWFKTFgFShPPQkDEemVbiFyondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'JAAAon', name: "Janus Henderson AAA CLO ETF", mint: 'KZtqx9BJbpcGY7vdzhqPXM3ECKChxE5YhXaDiwRondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'JNJon', name: "Johnson & Johnson", mint: 'KUXt7LzHWSQXp5eyqMZRxWjAP6yM8BUh4LRHwiwondo', provider: 'Ondo', sector: 'Health' },
  { symbol: 'UBERon', name: "Uber", mint: 'KJNeFW3kk3ycPjXpC6cbuyckjeYHacc2ekhtAi5ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'SNOWon', name: "Snowflake", mint: 'JmFLCBwoNvcXy6B2VqABg6m784ubkXpaEx3p7S5ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'SGOVon', name: "iShares 0-3 Month Treasury Bond ETF", mint: 'HjrN6ChZK2QRL6hMXayjGPLFvxhgjwKEy135VRjondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'RDDTon', name: "Reddit", mint: 'HXFrTf9v9NdjGUTnx4sojR3Cf92hoBsQFUxKTN7ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'PBRon', name: "Petrobras", mint: 'GRciFCqJ5y2hbiD6U5mGkohY65BZTXGuGUrCqf7ondo', provider: 'Ondo', sector: 'Energy' },
  { symbol: 'NOWon', name: "ServiceNow", mint: 'G7pTVoSECz5RQWubEnTP7AC83KHUsSyoiqYR1R2ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'MRVLon', name: "Marvell Technology", mint: 'FovBwhoV5KQjZCdhoM6jgXYwXLX3F8vgAfvmLH7ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'CVNAon', name: "Carvana", mint: 'FGmUDXqA3AbWfo5b3NUcsvwoUFCF4tr9ea6uercondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'MAon', name: "Mastercard", mint: 'EsVHcyRxXFJCLMiuYLWhoDygrNe1BJGpYeZ17X7ondo', provider: 'Ondo', sector: 'Finance' },
  { symbol: 'LINon', name: "Linde plc", mint: 'Edik9MoFp8LAXS9HNu2gRFyihwYqDqv4ZmNmVT9ondo', provider: 'Ondo', sector: 'Industrial' },
  { symbol: 'MELIon', name: "MercadoLibre", mint: 'EWwdgGshGngcMpDV34pWZRSu5bkAuiKuKTTHKQ8ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'MARAon', name: "MARA Holdings", mint: 'ETCJUmuhs5aY62xgEVWCZ5JR8KPdeXUaJz3LuC5ondo', provider: 'Ondo', sector: 'Crypto' },
  { symbol: 'SQQQon', name: "ProShares UltraPro Short QQQ", mint: 'D1tu7Fnm3cCpKyyPXrqm5GXShPqMj7a2SEjjq9fondo', provider: 'Ondo', sector: 'ETF' },
  { symbol: 'DEon', name: "Deere", mint: 'CqQyAZjB9LGFTG95eiadGTkfhd9QA12ProeKsQmondo', provider: 'Ondo', sector: 'Industrial' },
  { symbol: 'ANETon', name: "Arista Networks", mint: 'Cq6QtvHpXbJWtFaiMhUDtHy8YVZ95gcD1oZ1cohondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'INTUon', name: "Intuit", mint: 'CozoH5HBTyyeYSQxHcWpGzd4Sq5XBaKzBzvTtN3ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'AMCon', name: "AMC Entertainment", mint: 'C9xNaNujcF1a5fidWAAFReFYqhLRVbyk4yPyGqzondo', provider: 'Ondo', sector: 'Media' },
  { symbol: 'GSon', name: "Goldman Sachs", mint: 'BchJRy2snmhJZf3rQ9LJ3ePs2BGfYgfvQNo31d2ondo', provider: 'Ondo', sector: 'Finance' },
  { symbol: 'XYZon', name: "Block", mint: 'BWxe2FVciUbwrCUZQPUKiREBh5LmVa5AiUqNLAkondo', provider: 'Ondo', sector: 'Finance' },
  { symbol: 'HOODon', name: "Robinhood Markets", mint: 'BVdXGvmgi6A9oAiwWvBvP76fyTqcCNRJMM7zMN6ondo', provider: 'Ondo', sector: 'Finance' },
  { symbol: 'FUTUon', name: "Futu Holdings", mint: 'Ao5rKFRQ54W3DKSAtqfhBRPNHewwWRLNLao2JL9ondo', provider: 'Ondo', sector: 'Finance' },
  { symbol: 'RIVNon', name: "Rivian Automotive", mint: 'AXRsYFt7TXNQ3DcY6BkvRgPV6VsYMURyDtaeudjondo', provider: 'Ondo', sector: 'EV' },
  { symbol: 'CATon', name: "Caterpillar", mint: 'AErxJJxGbc9cZzZoZepN62BNfg5RXns8tmEc3Zpondo', provider: 'Ondo', sector: 'Industrial' },
  { symbol: 'BLSHon', name: "Bullish", mint: 'A9PFmw9Hu8zzxDUoU351pio1E1XWBWBfWnjT9qoondo', provider: 'Ondo', sector: 'Crypto' },
  { symbol: 'AALon', name: "American Airlines Group", mint: '9wYZetvT8J2ptfsRca5gzLBGvcUug38mp9yT3xaondo', provider: 'Ondo', sector: 'Consumer' },
  { symbol: 'TCOMon', name: "Trip.com Group", mint: '9PMjLqd8zPdKkJUXarnit5t7tPL3cCscwHzy7ATondo', provider: 'Ondo', sector: 'Consumer' },
  { symbol: 'DASHon', name: "DoorDash", mint: '83P1gCFBZfGRCwJuBt9juxJKEsZwejJoG66eTZ6ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'TXNon', name: "Texas Instruments", mint: '81xLFvCzFaUM3KDxSHC75pXu3RPCeSeCbmGBY8aondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'ONDSon', name: "Ondas Holdings", mint: '7qy1j4Mechfyr6uAST3djH4vk4kiEYC2cjEytXdondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'AMATon', name: "Applied Materials", mint: '7eRX747PSbVtGVx3qD5UFdkNM2BfTy86ikUiCMhondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'CEGon', name: "Constellation Energy", mint: '7NWHifsBnn9DimUeNnsHdEXkTZhXmJTiXxcCngBondo', provider: 'Ondo', sector: 'Energy' },
  { symbol: 'COSTon', name: "Costco", mint: '6btaz134wjHkR8sqhAYrtSM6tavftfxnRvnyMd8ondo', provider: 'Ondo', sector: 'Consumer' },
  { symbol: 'CMGon', name: "Chipotle", mint: '5owVsVFSHACQuippFYdLp3qWRobp2EGcwxMmsr6ondo', provider: 'Ondo', sector: 'Consumer' },
  { symbol: 'Fon', name: "Ford Motor", mint: '5hT2o25X9tGXipwhLckaUdgnxrZ6Y8eiUwdhpLeondo', provider: 'Ondo', sector: 'Auto' },
  { symbol: 'BIDUon', name: "Baidu", mint: '54CoRF2FYMZNJg9tS36xq5BUcLZ7rju1r59jGc2ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'BAon', name: "Boeing", mint: '1YVZ4LGpq8CAhpdpm3mgy7GgPb83gJczCpxLUQ3ondo', provider: 'Ondo', sector: 'Industrial' },
  { symbol: 'AXPon', name: "American Express", mint: '1WxT6NdK7uqpfXuKpALxL2n3f7Rq61XXeHA8UM4ondo', provider: 'Ondo', sector: 'Finance' },
  { symbol: 'ISRGon', name: "Intuitive Surgical", mint: '1MGRpPrkhEsCm2GCWD3rsvEU77xTTLAzfKXeFgFondo', provider: 'Ondo', sector: 'Health' },
  { symbol: 'OXYon', name: "Occidental Petroleum", mint: '1GNFMryQ6c9ZpMhgNimmsbtgYM21qnBJgRAFoNiondo', provider: 'Ondo', sector: 'Energy' },
  { symbol: 'ARMon', name: "Arm Holdings plc", mint: '15SsCZqCsM9fZGhTmP4rdJTPT9WGZKazDSsgeQ8ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'BILIon', name: "Bilibili", mint: '14kLsQVmc64qZexYuR4XGop9y8BeMkd77pJUm1Rhondo', provider: 'Ondo', sector: 'Media' },
  { symbol: 'APPon', name: "AppLovin", mint: '14Z8rQQe2Aza33YgEUmj3g3QGNz8DXLiFPuCnsD1ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'APOon', name: "Apollo Global Management", mint: '14VXAhoa1R74vi1ZuiQyGLJrnDMfoFBPJSCpGVz3ondo', provider: 'Ondo', sector: 'Finance' },
  { symbol: 'KLACon', name: "KLA", mint: '149o8ppQf9SzKCKXZ4v3dzHkwumvtQSRzSEkr29uondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'ONon', name: "ON Semiconductor", mint: '13qtwy5fZi9Przz14pzo9xqFSr8QHmLyUpUCvP1xondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'ACNon', name: "Accenture", mint: '12LxMMJYVSf4LoeqjFE47BQQNRciaH9E3nbDfjH4ondo', provider: 'Ondo', sector: 'Tech' },
  { symbol: 'DNNon', name: "Denison Mines", mint: '12J2LD3tuLfdiVKnWZMHRMrbnXDY9rM4yqVLUa5yondo', provider: 'Ondo', sector: 'Energy' },
  { symbol: 'RTXon', name: "RTX", mint: '12BvLZtzjdssAycxPeBQUjukhmgQpULAvy6SroYdondo', provider: 'Ondo', sector: 'Defense' },
  { symbol: 'ABTon', name: "Abbott", mint: '129gRoHKhVg7CvPMrqVsEB4uYZo6zV4yDZX6NBg9ondo', provider: 'Ondo', sector: 'Health' },
  { symbol: 'ABNBon', name: "Airbnb", mint: '128qNYovdGv2YqayErcJgU7gDwbNVX1VuoxbtWz8ondo', provider: 'Ondo', sector: 'Consumer' },
];

// ─── Combined ──────────────────────────────────────────────────────────────────

// Remove placeholder tokens with empty mints
export const ALL_TOKENS = [...XSTOCKS, ...PRESTOCKS, ...ONDO_TOKENS].filter(t => t.mint !== '');
